#!/usr/bin/env python3
"""Shared, dependency-light helpers for the reviewer reproduction scripts.

The experiment drivers intentionally live outside ``src/``, ``applications/``,
and ``advanced/``.  They call the paper code as subprocesses and keep every
generated artifact below a caller-selected output directory.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping, Sequence


REPRODUCTION_ROOT = Path(__file__).resolve().parent
REPO_ROOT = REPRODUCTION_ROOT.parent
INSTANCE_ROOT = REPRODUCTION_ROOT / "instances"
DEFAULT_ENLIGHT_HARD_MPS = INSTANCE_ROOT / "miplib" / "enlight_hard.mps.gz"
DEFAULT_MATPOWER_DIR = INSTANCE_ROOT / "matpower"
DEFAULT_ARCHIVE = REPO_ROOT / "experiments_logs.zip"
PAPER_SEEDS = (111, 222, 333, 444, 555)


@dataclass(frozen=True)
class Job:
    """One isolated experiment subprocess."""

    name: str
    command: tuple[str, ...]

    def __init__(self, name: str, command: Sequence[object]):
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "command", tuple(str(value) for value in command))


@dataclass(frozen=True)
class JobResult:
    name: str
    command: tuple[str, ...]
    log_path: str
    returncode: int
    elapsed_seconds: float
    skipped: bool


def add_common_arguments(
    parser: argparse.ArgumentParser,
    *,
    default_output: Path,
    extra_modes: Sequence[str] = (),
) -> None:
    """Add the common execution and artifact arguments to a section CLI."""

    modes = ("archived", "parse", "smoke", "full", *extra_modes)
    mode_help = (
        "archived: rebuild from experiments_logs.zip; parse: rebuild from "
        "--logs; smoke/full: execute a bounded/complete fresh sweep"
    )
    if "reported" in extra_modes:
        mode_help += (
            "; reported: rerun and pixel-validate the historical submitted panels"
        )
    parser.add_argument(
        "--mode",
        choices=modes,
        default="archived",
        help=mode_help,
    )
    parser.add_argument(
        "--archive",
        type=Path,
        default=DEFAULT_ARCHIVE,
        help=(
            "Path to experiments_logs.zip or an extracted experiments_logs "
            "directory; required by archived mode and optional for stronger "
            "full-mode comparison"
        ),
    )
    parser.add_argument(
        "--logs",
        type=Path,
        help="Existing raw-log directory used with --mode parse.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_output,
        help=(
            "Base artifact directory. The selected mode writes below BASE/MODE "
            "so smoke, archived, parse, and full outputs cannot overwrite one another."
        ),
    )
    parser.add_argument("--julia", default="julia", help="Julia executable (default: julia).")
    parser.add_argument("--threads", type=int, default=16, help="Julia threads per job (paper: 16).")
    parser.add_argument(
        "--jobs",
        type=int,
        default=1,
        help="Concurrent Julia processes (default: 1; each process already uses --threads).",
    )
    parser.add_argument(
        "--no-resume",
        action="store_true",
        help="Re-run jobs whose successful result marker and log already exist.",
    )
    parser.add_argument("--no-plots", action="store_true", help="Write CSVs but skip plot generation.")


def validate_common_arguments(args: argparse.Namespace) -> None:
    if args.threads < 1:
        raise SystemExit("--threads must be at least 1")
    if args.jobs < 1:
        raise SystemExit("--jobs must be at least 1")
    if args.mode == "parse" and args.logs is None:
        raise SystemExit("--mode parse requires --logs")
    if args.mode == "archived" and not args.archive.exists():
        raise SystemExit(
            f"Archive not found: {args.archive}\n"
            "Pass --archive /path/to/experiments_logs.zip or use --mode full/smoke."
        )


def prepare_output(path: Path) -> Path:
    output = path.expanduser().resolve()
    (output / "raw").mkdir(parents=True, exist_ok=True)
    (output / "figures").mkdir(parents=True, exist_ok=True)
    return output


def prepare_mode_output(path: Path, mode: str) -> Path:
    """Create and identify an output directory dedicated to one CLI mode.

    The --output option is a base directory. Appending the mode prevents a
    quick smoke run from replacing paper-grid figures generated by full or
    archived mode. Accepting a base that already ends in the mode keeps
    explicit paths such as --output /tmp/run/smoke unsurprising.
    """

    if mode not in {
        "archived",
        "archived-source",
        "parse",
        "reported",
        "smoke",
        "full",
        "table",
    }:
        raise ValueError(f"Unsupported output mode: {mode!r}")
    base = path.expanduser().resolve()
    output = prepare_output(base if base.name == mode else base / mode)
    artifact_scopes = {
        "archived": "archived_reconstruction",
        "archived-source": "reported_source_preservation",
        "parse": "caller_supplied_parse_input",
        "reported": "fresh_reported_historical_workflow",
        "smoke": "validation_only_subset",
        "full": "fresh_paper_grid",
        "table": "static_configuration_export",
    }
    publication_warning = None
    if mode == "smoke":
        publication_warning = (
            "Smoke artifacts validate one documented subset and are not the complete "
            "paper table or figure."
        )
    elif mode == "reported":
        publication_warning = (
            "Reported mode follows the historical workflow that generated the "
            "published panels; smoke/full follow the literal manuscript algorithm."
        )

    profile = {
        "mode": mode,
        "artifact_scope": artifact_scopes[mode],
        "publication_warning": publication_warning,
    }
    _write_json_atomic(output / "artifact_profile.json", profile)
    return output


def resolve_julia(executable: str) -> str:
    resolved = shutil.which(executable)
    if resolved is None:
        candidate = Path(executable).expanduser()
        if candidate.is_file():
            return str(candidate.resolve())
        raise SystemExit(f"Julia executable not found: {executable}")
    return resolved


def legacy_workdir() -> Path:
    """Return the cwd required by the branch's existing warmup scripts.

    ``warmup.jl`` and ``advanced/warmup.jl`` resolve local packages through the
    literal relative path ``PDMO.jl``.  Refuse an ambiguous clone name rather
    than silently developing a different checkout.
    """

    if REPO_ROOT.name != "PDMO.jl":
        raise SystemExit(
            "The existing experiment entry points require the checkout directory to be named "
            f"PDMO.jl (current: {REPO_ROOT}). Rename it or use --mode archived/parse."
        )
    return REPO_ROOT.parent


def julia_command(julia: str, threads: int, script: Path, *arguments: object) -> tuple[str, ...]:
    return (
        resolve_julia(julia),
        "--startup-file=no",
        "-t",
        str(threads),
        str(script.resolve()),
        *(str(value) for value in arguments),
    )


def _is_julia_command(command: Sequence[str]) -> bool:
    """Return whether a subprocess command directly launches Julia."""

    if not command:
        return False
    executable = Path(command[0]).name.lower()
    return executable in {"julia", "julia.exe"} or executable.startswith("julia-")


def _sanitize_julia_environment(
    environment: Mapping[str, str],
) -> tuple[dict[str, str], list[str]]:
    """Remove only active-Conda library entries that can break Julia JLLs."""

    sanitized = dict(environment)
    conda_prefix = sanitized.get("CONDA_PREFIX")
    library_path = sanitized.get("LD_LIBRARY_PATH")
    if not conda_prefix or not library_path:
        return sanitized, []

    conda_libraries = {
        os.path.normpath(str(Path(conda_prefix).expanduser() / "lib")),
        os.path.normpath(str(Path(conda_prefix).expanduser() / "lib64")),
    }
    kept: list[str] = []
    removed: list[str] = []
    for entry in library_path.split(os.pathsep):
        if entry and os.path.normpath(os.path.expanduser(entry)) in conda_libraries:
            removed.append(entry)
        else:
            kept.append(entry)

    if kept:
        sanitized["LD_LIBRARY_PATH"] = os.pathsep.join(kept)
    else:
        sanitized.pop("LD_LIBRARY_PATH", None)
    return sanitized, removed


def _safe_job_path(root: Path, name: str, suffix: str) -> Path:
    relative = Path(name)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"Unsafe job name: {name!r}")
    return root / relative.parent / f"{relative.name}{suffix}"


def _write_json_atomic(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)


def run_jobs(
    jobs: Sequence[Job],
    *,
    log_root: Path,
    cwd: Path,
    workers: int = 1,
    resume: bool = True,
    environment: Mapping[str, str] | None = None,
) -> list[JobResult]:
    """Run independent jobs with merged stdout/stderr and resumable markers."""

    log_root.mkdir(parents=True, exist_ok=True)
    child_env = os.environ.copy()
    if environment:
        child_env.update({str(key): str(value) for key, value in environment.items()})

    def run_one(job: Job) -> JobResult:
        log_path = _safe_job_path(log_root, job.name, ".log")
        command_path = _safe_job_path(log_root, job.name, ".command.json")
        result_path = _safe_job_path(log_root, job.name, ".result.json")
        log_path.parent.mkdir(parents=True, exist_ok=True)
        job_env = child_env
        environment_adjustments: dict[str, object] = {}
        if _is_julia_command(job.command):
            job_env, removed = _sanitize_julia_environment(child_env)
            if removed:
                environment_adjustments["removed_ld_library_path_entries"] = removed

        if resume and log_path.is_file() and result_path.is_file():
            try:
                prior = json.loads(result_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                prior = {}
            prior_adjustments = prior.get("environment_adjustments")
            if (
                prior.get("returncode") == 0
                and tuple(prior.get("command", ())) == job.command
                and (
                    prior_adjustments is None
                    or prior_adjustments == environment_adjustments
                )
            ):
                return JobResult(
                    name=job.name,
                    command=job.command,
                    log_path=str(log_path),
                    returncode=0,
                    elapsed_seconds=float(prior.get("elapsed_seconds", 0.0)),
                    skipped=True,
                )

        started_at = datetime.now(timezone.utc)
        started = time.monotonic()
        _write_json_atomic(
            command_path,
            {
                "command": list(job.command),
                "cwd": str(cwd),
                "environment_adjustments": environment_adjustments,
                "started_at_utc": started_at.isoformat(),
            },
        )
        temporary_log_path = log_path.with_suffix(log_path.suffix + ".tmp")
        with temporary_log_path.open("w", encoding="utf-8") as stream:
            completed = subprocess.run(
                job.command,
                cwd=cwd,
                env=job_env,
                stdout=stream,
                stderr=subprocess.STDOUT,
                check=False,
            )
        temporary_log_path.replace(log_path)
        elapsed = time.monotonic() - started
        payload = {
            "command": list(job.command),
            "cwd": str(cwd),
            "environment_adjustments": environment_adjustments,
            "started_at_utc": started_at.isoformat(),
            "finished_at_utc": datetime.now(timezone.utc).isoformat(),
            "elapsed_seconds": elapsed,
            "returncode": completed.returncode,
            "log_path": str(log_path),
        }
        _write_json_atomic(result_path, payload)
        return JobResult(
            name=job.name,
            command=job.command,
            log_path=str(log_path),
            returncode=completed.returncode,
            elapsed_seconds=elapsed,
            skipped=False,
        )

    results: list[JobResult] = []
    if workers == 1:
        for index, job in enumerate(jobs, 1):
            print(f"[{index}/{len(jobs)}] {job.name}", flush=True)
            result = run_one(job)
            state = "resumed" if result.skipped else f"exit={result.returncode}"
            print(f"  {state}; log={result.log_path}", flush=True)
            results.append(result)
    else:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = {pool.submit(run_one, job): job for job in jobs}
            for future in as_completed(futures):
                result = future.result()
                state = "resumed" if result.skipped else f"exit={result.returncode}"
                print(f"[{result.name}] {state}; log={result.log_path}", flush=True)
                results.append(result)
    return sorted(results, key=lambda item: item.name)


def failed_jobs(results: Sequence[JobResult]) -> list[JobResult]:
    return [result for result in results if result.returncode != 0]


def collect_logs(root: Path) -> list[Path]:
    root = root.expanduser().resolve()
    if not root.is_dir():
        raise SystemExit(f"Log directory not found: {root}")
    return sorted(root.rglob("*.log"))


def _find_section_directory(root: Path, section_relative: str) -> Path:
    wanted = Path(section_relative)
    candidates = [root / wanted, root / "experiments_logs" / wanted, root]
    for candidate in candidates:
        if candidate.is_dir() and (
            candidate.name == wanted.name or candidate != root or any(candidate.rglob("stdout.log"))
        ):
            return candidate
    matches = [path for path in root.rglob(wanted.name) if path.is_dir()]
    if len(matches) == 1:
        return matches[0]
    raise SystemExit(f"Could not locate {section_relative!r} below {root}")


@contextmanager
def materialize_archive_section(archive: Path, section_relative: str) -> Iterator[Path]:
    """Yield an extracted section directory from a zip or existing directory."""

    archive = archive.expanduser().resolve()
    if archive.is_dir():
        yield _find_section_directory(archive, section_relative)
        return
    if not archive.is_file():
        raise SystemExit(f"Archive not found: {archive}")

    with tempfile.TemporaryDirectory(prefix="pdmo-reproduction-") as temp_name:
        temporary_root = Path(temp_name)
        with zipfile.ZipFile(archive) as zipped:
            selected = []
            section_parts = ("experiments_logs", *Path(section_relative).parts)
            for member in zipped.infolist():
                parts = Path(member.filename).parts
                if any(parts[index : index + len(section_parts)] == section_parts for index in range(len(parts))):
                    selected.append(member)
            if not selected:
                raise SystemExit(f"Section {section_relative!r} is absent from {archive}")
            for member in selected:
                target = (temporary_root / member.filename).resolve()
                try:
                    target.relative_to(temporary_root)
                except ValueError as error:
                    raise SystemExit(f"Unsafe archive member: {member.filename}") from error
                if member.is_dir():
                    target.mkdir(parents=True, exist_ok=True)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    with zipped.open(member) as source, target.open("wb") as destination:
                        shutil.copyfileobj(source, destination)
        yield _find_section_directory(temporary_root, section_relative)


def source_logs(args: argparse.Namespace, archive_section: str, fresh_log_root: Path):
    """Return a context manager yielding the raw-log source for the selected mode."""

    if args.mode == "archived":
        return materialize_archive_section(args.archive, archive_section)
    if args.mode == "parse":
        return _yield_path(args.logs.expanduser().resolve())
    return _yield_path(fresh_log_root)


@contextmanager
def _yield_path(path: Path) -> Iterator[Path]:
    yield path


def write_csv(path: Path, fieldnames: Sequence[str], rows: Iterable[Mapping[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def write_json(path: Path, payload: Any) -> None:
    _write_json_atomic(path, payload)


def arithmetic_mean(values: Iterable[float]) -> float:
    items = list(values)
    if not items:
        raise ValueError("Cannot average an empty sequence")
    return sum(items) / len(items)


def sample_std(values: Iterable[float]) -> float:
    items = list(values)
    if len(items) < 2:
        return 0.0
    center = arithmetic_mean(items)
    return (sum((value - center) ** 2 for value in items) / (len(items) - 1)) ** 0.5


def get_pyplot():
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as pyplot
    except ImportError as error:
        raise SystemExit(
            "Plotting requires matplotlib. Install it with "
            "`python -m pip install -r reproduction/requirements.txt`."
        ) from error
    return pyplot


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _capture(command: Sequence[str], cwd: Path | None = None) -> str | None:
    try:
        result = subprocess.run(
            command,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def _json_safe(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (tuple, list)):
        return [_json_safe(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    return value


def write_provenance(
    output: Path,
    *,
    section: str,
    args: argparse.Namespace,
    jobs: Sequence[Job] = (),
    inputs: Sequence[Path] = (),
    notes: Sequence[str] = (),
) -> Path:
    git_commit = _capture(("git", "rev-parse", "HEAD"), REPO_ROOT)
    git_status = _capture(("git", "status", "--short"), REPO_ROOT)
    julia_version = (
        _capture((args.julia, "--version"))
        if args.mode in ("smoke", "full", "reported")
        else None
    )
    input_records = []
    for path in inputs:
        expanded = path.expanduser().resolve()
        record: dict[str, Any] = {"path": str(expanded), "exists": expanded.exists()}
        if expanded.is_file():
            record["size_bytes"] = expanded.stat().st_size
            record["sha256"] = sha256_file(expanded)
        input_records.append(record)
    payload = {
        "section": section,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "arguments": _json_safe(vars(args)),
        "repository": {
            "path": str(REPO_ROOT),
            "git_commit": git_commit,
            "git_status_short": git_status,
        },
        "runtime": {
            "python": sys.version,
            "julia": julia_version,
            "platform": platform.platform(),
            "machine": platform.machine(),
            "processor": platform.processor(),
            "cpu_count": os.cpu_count(),
        },
        "inputs": input_records,
        "jobs": [{"name": job.name, "command": list(job.command)} for job in jobs],
        "notes": list(notes),
    }
    path = output / "provenance.json"
    write_json(path, payload)
    return path


def job_results_as_dicts(results: Sequence[JobResult]) -> list[dict[str, Any]]:
    return [asdict(result) for result in results]
