#!/usr/bin/env python3
"""Reproduce Section 3.3 distributed DC-OPF Figures 13 and 14."""

from __future__ import annotations

import argparse
import math
import os
import re
import shutil
import subprocess
import sys

if __package__:
    from . import common as _common
    sys.modules.setdefault("common", _common)
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from common import (
    DEFAULT_MATPOWER_DIR,
    REPRODUCTION_ROOT,
    REPO_ROOT,
    Job,
    _sanitize_julia_environment,
    add_common_arguments,
    arithmetic_mean,
    collect_logs,
    failed_jobs,
    get_pyplot,
    job_results_as_dicts,
    julia_command,
    legacy_workdir,
    prepare_mode_output,
    run_jobs,
    sha256_file,
    source_logs,
    validate_common_arguments,
    write_csv,
    write_json,
    write_provenance,
)


ARCHIVE_SECTION = "3-3-opf_distrun"
METHODS = ("BFS", "MILP", "GNN")
FIGURE_13_CASES = (
    "case30",
    "case57",
    "case89pegase",
    "case118",
    "case300",
    "case1888rte",
)
FIGURE_13_PARTITIONS = tuple(range(3, 11))
FIGURE_14_PARTITIONS = tuple(range(13, 19))

TOLERANCE = 1.0e-4
MAX_ITERATIONS = 1_000_000
TIME_LIMIT_SECONDS = 7_200.0
LOG_INTERVAL = 100
R_VALUE = 1.0e4
SEED = 126

METHOD_COLORS = {
    "BFS": "#f39c12",
    "MILP": "#27ae60",
    "GNN": "#9467bd",
}
METHOD_LIGHT_COLORS = {
    "BFS": "#f8c471",
    "MILP": "#7ddc98",
    "GNN": "#c5b0d5",
}

# These are the only archived jobs used by Figures 13 and 14.  Keeping the
# identifiers explicit prevents accidental inclusion of archived/, case141*,
# or the earlier rho=1000 case57 run that did not generate the published panels.
ARCHIVED_JOB_IDS = {
    "case30": tuple(str(value) for value in range(51455118, 51455126)),
    "case57": tuple(str(value) for value in range(51455152, 51455160)),
    "case89pegase": tuple(str(value) for value in range(51455204, 51455212)),
    "case118": tuple(str(value) for value in range(51455233, 51455241)),
    "case300": tuple(str(value) for value in range(51455276, 51455284)),
    "case1888rte": tuple(str(value) for value in range(51455616, 51455624)),
    "case57_flip_2000": tuple(str(value) for value in range(51523865, 51523871)),
}

FRESH_FIGURE_14_PROFILE = {
    "classification": "manuscript_literal_fresh",
    "initial_rho": 1000.0,
    "source": "fresh Julia execution",
    "archive_folder": None,
    "archive_job_ids": [],
}
REPORTED_FIGURE_14_PROFILE = {
    "classification": "historical_reported_archive",
    "initial_rho": 2000.0,
    "source": "experiments_logs.zip retained jobs that generated the arXiv panels",
    "archive_folder": "case57_flip_2000",
    "archive_job_ids": list(ARCHIVED_JOB_IDS["case57_flip_2000"]),
    "manuscript_caption_initial_rho": 1000.0,
    "discrepancy": (
        "The Figure 14 caption states rho=1000, but the retained source panels and "
        "their numerical data were generated by these rho=2000 jobs."
    ),
}

PUBLISHED_FIGURE_14_SOURCE_PANELS = {
    "opf_flip_iterations.png": (
        "figure_14_iterations.png",
        "158127ef0a97a871c4c7be4f5f28e32cf8788bda89cf73812334a5b61f819f3e",
    ),
    "opf_flip_stacked_time.png": (
        "figure_14_stacked_time.png",
        "940e223b5ea9eeceaeb5ccaaec3ad74239a5829a2a89040b0364f60d31e178ae",
    ),
}

OBJECTIVE_FINGERPRINTS = {
    "case30": 565.2059663999221,
    "case57": 41006.73694205554,
    "case89pegase": 5733.370870000001,
    "case118": 125947.88140239994,
    "case300": 706292.3242436099,
    "case1888rte": 59110.49999102508,
}

MATPOWER_8_1_SHA256 = {
    "case30": "3d9030311259b553be85d02336b7e1bcb24ec04775bee6671bdb62d18e4e2137",
    "case57": "2218325a6e8fe6c7b8b28202f523670459268075a6fd41b4959d66f17d47d28b",
    "case89pegase": "7eb25c591f04a08dcd99ab433451054eaafd8bb3d7999d9279a8ddb23d8ffe58",
    "case118": "bc2e6f22b4b9e776572885ee4b50e4f4ab2ee0c5577e9126e86d906f14c4b5f7",
    "case300": "69a90280e999ef533d94656e0fbc08311f1347c962dd2753ff2005ff5e3f9ac5",
    "case1888rte": "df675cd826bb300e91596795ee3258a70deb81f0329dbc49ccf24c6048668037",
}

# Exact archived values for the documented smoke point (Figure 13, case30,
# P=3). Iterations are deterministic; timing is retained for context only.
REFERENCE_SMOKE_CASE30_P3 = {
    "BFS": {
        "iterations": 136.0,
        "partition_time_seconds": 0.0,
        "admm_time_seconds": 2.71,
    },
    "MILP": {
        "iterations": 136.0,
        "partition_time_seconds": 5.587,
        "admm_time_seconds": 1.03,
    },
    "GNN": {
        "iterations": 136.0,
        "partition_time_seconds": 4.841,
        "admm_time_seconds": 1.02,
    },
}

# Paper/archive aggregate references.  Figure 13 values are arithmetic means
# over P=3,...,10.  Figure 14 has one value per partition count.
REFERENCE_FIGURE_13 = {
    "case30": {
        "BFS": (394.625, 5.488750),
        "MILP": (347.750, 9.231250),
        "GNN": (298.500, 7.833625),
    },
    "case57": {
        "BFS": (1201.250, 16.858750),
        "MILP": (929.500, 17.280750),
        "GNN": (1132.625, 19.039500),
    },
    "case89pegase": {
        "BFS": (81478.000, 2085.131250),
        "MILP": (59878.750, 1540.727250),
        "GNN": (86547.375, 2229.532625),
    },
    "case118": {
        "BFS": (1682.000, 33.516250),
        "MILP": (1503.750, 32.957375),
        "GNN": (1659.750, 34.865625),
    },
    "case300": {
        "BFS": (9519.500, 364.721250),
        "MILP": (5807.875, 226.485375),
        "GNN": (6341.000, 246.576750),
    },
    "case1888rte": {
        "BFS": (12791.000, 2962.001250),
        "MILP": (9252.250, 2185.314500),
        "GNN": (9103.125, 2152.359250),
    },
}

# Exact raw values behind the published arXiv Figure 14 panels. Tuple fields
# are (iterations, partition seconds, ADMM seconds). These retained jobs used
# rho=2000 even though the manuscript caption states rho=1000.
REFERENCE_FIGURE_14 = {
    13: {
        "BFS": (10120.0, 0.0, 165.04),
        "MILP": (8484.0, 1.178, 137.84),
        "GNN": (9430.0, 4.590, 153.22),
    },
    14: {
        "BFS": (10608.0, 0.0, 190.83),
        "MILP": (10610.0, 1.284, 187.99),
        "GNN": (16978.0, 4.585, 298.67),
    },
    15: {
        "BFS": (13218.0, 0.0, 250.52),
        "MILP": (14218.0, 1.553, 259.22),
        "GNN": (10274.0, 4.792, 187.26),
    },
    16: {
        "BFS": (16482.0, 0.0, 307.54),
        "MILP": (15966.0, 1.154, 298.02),
        "GNN": (22012.0, 4.632, 415.50),
    },
    17: {
        "BFS": (10006.0, 0.0, 205.82),
        "MILP": (9621.0, 1.573, 194.93),
        "GNN": (8752.0, 4.953, 179.76),
    },
    18: {
        "BFS": (34832.0, 0.0, 725.42),
        "MILP": (34046.0, 1.260, 697.74),
        "GNN": (34046.0, 4.854, 703.55),
    },
}

RUN_FIELDS = (
    "figure",
    "case",
    "partition_number",
    "method",
    "case_file",
    "admm_solver",
    "initial_rho",
    "tolerance",
    "max_iterations",
    "time_limit_seconds",
    "log_interval",
    "r_value",
    "seed",
    "threads",
    "partition_time_seconds",
    "admm_time_seconds",
    "total_time_seconds",
    "iterations",
    "admm_objective",
    "termination_status",
    "primal_residual_l2",
    "primal_residual_linf",
    "dual_residual_l2",
    "dual_residual_linf",
    "true_dc_objective",
    "true_objective_difference",
    "log_path",
)

AGGREGATE_FIELDS = (
    "figure",
    "case",
    "partition_number",
    "aggregation",
    "method",
    "sample_count",
    "partition_time_seconds",
    "admm_time_seconds",
    "total_time_seconds",
    "iterations",
    "normalized_partition_time",
    "normalized_admm_time",
    "normalized_total_time",
    "normalized_iterations",
)


@dataclass(frozen=True)
class ExperimentSpec:
    figure: int
    case: str
    partition_number: int
    solver: str
    rho: float
    archive_folder: str
    archive_job_id: str | None = None

    @property
    def key(self) -> tuple[int, str, int]:
        return (self.figure, self.case, self.partition_number)

    @property
    def job_name(self) -> str:
        return f"figure_{self.figure}/{self.case}/p{self.partition_number:02d}"


def _full_specs(
    *,
    figure_14_rho: float,
    figure_14_archive_folder: str,
    figure_14_job_ids: Sequence[str] | None,
) -> tuple[ExperimentSpec, ...]:
    specs: list[ExperimentSpec] = []
    for case in FIGURE_13_CASES:
        job_ids = ARCHIVED_JOB_IDS[case]
        for offset, partition_number in enumerate(FIGURE_13_PARTITIONS):
            specs.append(
                ExperimentSpec(
                    13,
                    case,
                    partition_number,
                    "original",
                    100.0,
                    case,
                    job_ids[offset],
                )
            )
    flip_ids = tuple(figure_14_job_ids or ())
    for offset, partition_number in enumerate(FIGURE_14_PARTITIONS):
        specs.append(
            ExperimentSpec(
                14,
                "case57",
                partition_number,
                "doubly",
                figure_14_rho,
                figure_14_archive_folder,
                flip_ids[offset] if flip_ids else None,
            )
        )
    return tuple(specs)


FRESH_FULL_SPECS = _full_specs(
    figure_14_rho=1000.0,
    figure_14_archive_folder="case57_flip_1000",
    figure_14_job_ids=None,
)
ARCHIVED_SPECS = _full_specs(
    figure_14_rho=2000.0,
    figure_14_archive_folder="case57_flip_2000",
    figure_14_job_ids=ARCHIVED_JOB_IDS["case57_flip_2000"],
)
SMOKE_SPECS = (FRESH_FULL_SPECS[0],)
FRESH_SPEC_BY_KEY = {spec.key: spec for spec in FRESH_FULL_SPECS}
ARCHIVED_SPEC_BY_KEY = {spec.key: spec for spec in ARCHIVED_SPECS}

def _experiment_profile(
    specs: Sequence[ExperimentSpec],
) -> dict[str, object]:
    figure_14_specs = [spec for spec in specs if spec.figure == 14]
    if not figure_14_specs:
        classification = "manuscript_literal_fresh_smoke"
        figure_14 = {**FRESH_FIGURE_14_PROFILE, "included": False}
    elif all(_close(spec.rho, 1000.0) for spec in figure_14_specs):
        classification = "manuscript_literal_fresh"
        figure_14 = {**FRESH_FIGURE_14_PROFILE, "included": True}
    elif all(_close(spec.rho, 2000.0) for spec in figure_14_specs):
        classification = "historical_reported_archive"
        figure_14 = {**REPORTED_FIGURE_14_PROFILE, "included": True}
    else:
        classification = "mixed_incompatible_profiles"
        figure_14 = {
            "classification": classification,
            "included": True,
            "initial_rhos": sorted({spec.rho for spec in figure_14_specs}),
            "source": "mixed profile; validation must reject this grid",
        }
    return {
        "classification": classification,
        "figure_13": {
            "initial_rho": 100.0,
            "solver": "original",
            "source": "same configuration in fresh and retained runs",
        },
        "figure_14": figure_14,
        "profiles_are_not_interchangeable": "Archived reported rho=2000 and fresh manuscript-literal rho=1000 results must not be merged.",
    }



def _resolve_python(value: Path | None) -> str:
    candidate = str(value) if value is not None else os.environ.get("PDMO_PYTHON", "")
    if not candidate:
        raise SystemExit(
            "Fresh GNN runs require PDMO_PYTHON. Pass --python /path/to/python "
            "or export PDMO_PYTHON before running."
        )
    expanded = Path(candidate).expanduser()
    if expanded.is_file():
        return str(expanded.resolve())
    resolved = shutil.which(candidate)
    if resolved:
        return resolved
    raise SystemExit(f"Python executable not found: {candidate}")


def _check_python_dependencies(executable: str) -> None:
    version_command = (
        executable,
        "-c",
        "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')",
    )
    try:
        version_result = subprocess.run(
            version_command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"Could not query Python environment {executable}: {error}") from error
    version_text = version_result.stdout.strip()
    try:
        version = tuple(int(value) for value in version_text.split("."))
    except ValueError as error:
        raise SystemExit(
            f"Could not parse Python version from {executable}: {version_text!r}"
        ) from error
    if version_result.returncode != 0 or len(version) != 2:
        raise SystemExit(
            f"Could not query Python version from {executable}: {version_text!r}"
        )
    if not ((3, 9) <= version < (3, 12)):
        raise SystemExit(
            "Fresh GNN runs require Python 3.9-3.11 "
            f"(selected {version_text}: {executable}). Python 3.12 is rejected "
            "because the current PyCall/Torch path can crash during interpreter finalization. "
            "Python 3.9 matches the archived experiment environment."
        )

    command = (
        executable,
        "-c",
        "import numpy, torch, torch_geometric; "
        "print(torch.__version__, torch_geometric.__version__, numpy.__version__)",
    )
    try:
        completed = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
            timeout=120,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"Could not validate GNN Python environment {executable}: {error}") from error
    if completed.returncode != 0:
        raise SystemExit(
            "The selected Python cannot import numpy, torch, and torch_geometric:\n"
            f"{completed.stdout.strip()}"
        )
    print(f"GNN Python environment: {completed.stdout.strip()}")


def _check_pycall_dependencies(julia: str, executable: str) -> None:
    script = REPRODUCTION_ROOT / "julia" / "check_pycall.jl"
    command = julia_command(julia, 1, script, executable)
    child_env, _ = _sanitize_julia_environment(os.environ)
    child_env["PDMO_PYTHON"] = executable
    try:
        completed = subprocess.run(
            command,
            cwd=REPO_ROOT,
            env=child_env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
            timeout=300,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"Could not validate Julia PyCall environment: {error}") from error
    if completed.returncode != 0:
        raise SystemExit(
            "The advanced Julia environment cannot use the selected GNN Python. "
            "Set PDMO_PYTHON and rerun advanced/warmup.jl, then retry:\n"
            f"{completed.stdout.strip()}"
        )
    print(completed.stdout.strip())


def _matpower_inputs(directory: Path, specs: Sequence[ExperimentSpec]) -> dict[str, Path]:
    directory = directory.expanduser().resolve()
    if not directory.is_dir():
        raise SystemExit(f"MATPOWER directory not found: {directory}")
    cases = tuple(dict.fromkeys(spec.case for spec in specs))
    inputs = {case: directory / f"{case}.m" for case in cases}
    missing = [path for path in inputs.values() if not path.is_file()]
    if missing:
        formatted = "\n".join(f"  - {path}" for path in missing)
        raise SystemExit(f"Required MATPOWER case files are missing:\n{formatted}")
    mismatched = []
    for case, path in inputs.items():
        observed = sha256_file(path)
        expected = MATPOWER_8_1_SHA256[case]
        if observed != expected:
            mismatched.append(f"{path}: expected {expected}, observed {observed}")
    if mismatched:
        formatted = "\n".join(f"  - {item}" for item in mismatched)
        raise SystemExit(
            "MATPOWER inputs do not match the pinned 8.1 paper files:\n" + formatted
        )
    return inputs


def _jobs_for_specs(
    args: argparse.Namespace,
    specs: Sequence[ExperimentSpec],
    case_files: Mapping[str, Path],
) -> list[Job]:
    runner = REPO_ROOT / "advanced" / "src" / "OPF" / "runDistributedOPF.jl"
    if not runner.is_file():
        raise SystemExit(f"Existing DC-OPF runner not found: {runner}")
    jobs: list[Job] = []
    for spec in specs:
        # All defaults are passed explicitly so later source-default changes cannot
        # silently alter the reviewer experiment.
        command = julia_command(
            args.julia,
            args.threads,
            runner,
            case_files[spec.case],
            spec.partition_number,
            spec.solver,
            f"{spec.rho:.1f}",
            f"{TOLERANCE:.1e}",
            MAX_ITERATIONS,
            f"{TIME_LIMIT_SECONDS:.1f}",
            LOG_INTERVAL,
            f"{R_VALUE:.1f}",
            SEED,
        )
        jobs.append(Job(spec.job_name, command))
    return jobs


def _archived_final_logs(section_root: Path) -> list[Path]:
    paths: list[Path] = []
    missing: list[Path] = []
    for spec in ARCHIVED_SPECS:
        assert spec.archive_job_id is not None
        path = section_root / spec.archive_folder / spec.archive_job_id / "stdout.log"
        if path.is_file():
            paths.append(path)
        else:
            missing.append(path)
    if missing:
        formatted = "\n".join(f"  - {path}" for path in missing)
        raise SystemExit(f"Final Section 3.3 archive logs are missing:\n{formatted}")
    return paths


def _preserve_reported_figure_14_panels(
    section_root: Path, output: Path
) -> dict[str, object]:
    source_root = section_root / "case57_flip_2000"
    target_root = output / "reported_source"
    target_root.mkdir(parents=True, exist_ok=True)
    errors: list[str] = []
    panels: list[dict[str, object]] = []
    for source_name, (target_name, expected_sha256) in PUBLISHED_FIGURE_14_SOURCE_PANELS.items():
        source = source_root / source_name
        target = target_root / target_name
        record: dict[str, object] = {
            "source": str(source),
            "output": str(target),
            "expected_sha256": expected_sha256,
            "exists": source.is_file(),
        }
        if not source.is_file():
            errors.append(f"Missing retained published Figure 14 panel: {source}")
            record["hash_matches"] = False
        else:
            source_sha256 = sha256_file(source)
            record["source_sha256"] = source_sha256
            if source_sha256 != expected_sha256:
                errors.append(
                    f"{source_name} SHA256 {source_sha256} does not match {expected_sha256}"
                )
                record["hash_matches"] = False
            else:
                shutil.copy2(source, target)
                output_sha256 = sha256_file(target)
                record["output_sha256"] = output_sha256
                record["hash_matches"] = output_sha256 == expected_sha256
                if output_sha256 != expected_sha256:
                    errors.append(f"Copied retained panel hash mismatch: {target}")
        panels.append(record)
    return {
        "status": "passed" if not errors else "failed",
        "classification": "byte_exact_reported_source_preservation",
        "figure_14_profile": REPORTED_FIGURE_14_PROFILE,
        "errors": errors,
        "panels": panels,
    }


def _archive_log_identifier(archive: Path, row: Mapping[str, object]) -> str:
    spec = ARCHIVED_SPEC_BY_KEY[
        (int(row["figure"]), str(row["case"]), int(row["partition_number"]))
    ]
    assert spec.archive_job_id is not None
    member = (
        Path("experiments_logs")
        / ARCHIVE_SECTION
        / spec.archive_folder
        / spec.archive_job_id
        / "stdout.log"
    )
    return f"{archive.expanduser().resolve()}::{member.as_posix()}"

def _match_required(pattern: str, text: str, label: str, path: Path) -> str:
    match = re.search(pattern, text, flags=re.MULTILINE)
    if not match:
        raise ValueError(f"{path}: missing {label}")
    return match.group(1).strip()


def _optional_float(pattern: str, text: str) -> float | str:
    match = re.search(pattern, text, flags=re.MULTILINE)
    return float(match.group(1)) if match else ""


def _detailed_results(text: str) -> list[dict[str, object]]:
    label_map = {
        "Objective": "objective",
        "Pres (L2)": "pres_l2",
        "Pres (LInf)": "pres_linf",
        "Dres (L2)": "dres_l2",
        "Dres (LInf)": "dres_linf",
        "Stop. Iter": "iterations",
        "Total Time": "total_time",
        "True Obj. Diff": "true_obj_diff",
    }
    results: list[dict[str, object]] = []
    current: dict[str, object] | None = None
    for line in text.splitlines():
        status_match = re.search(r"Solver Status\s*=\s*(\S+)", line)
        if status_match:
            if current is not None:
                results.append(current)
            current = {"status": status_match.group(1)}
            continue
        if current is None or "=" not in line:
            continue
        label, value = (part.strip() for part in line.split("=", 1))
        field = label_map.get(label)
        if field is None:
            continue
        token = value.split()[0]
        try:
            current[field] = int(token) if field == "iterations" else float(token)
        except ValueError:
            continue
    if current is not None:
        results.append(current)
    return results[-3:]


def _classify_spec(
    case: str, partition_number: int, solver: str, rho: float
) -> ExperimentSpec:
    if solver == "original" and math.isclose(rho, 100.0):
        key = (13, case, partition_number)
        candidates = FRESH_SPEC_BY_KEY
    elif solver == "doubly" and math.isclose(rho, 1000.0):
        key = (14, case, partition_number)
        candidates = FRESH_SPEC_BY_KEY
    elif solver == "doubly" and math.isclose(rho, 2000.0):
        key = (14, case, partition_number)
        candidates = ARCHIVED_SPEC_BY_KEY
    else:
        raise ValueError(
            f"unsupported Section 3.3 configuration case={case}, P={partition_number}, "
            f"solver={solver}, rho={rho}"
        )
    try:
        return candidates[key]
    except KeyError as error:
        raise ValueError(
            f"configuration is not in the Figure 13/14 paper grid: case={case}, "
            f"P={partition_number}, solver={solver}, rho={rho}"
        ) from error


def _parse_log(path: Path) -> tuple[ExperimentSpec, list[dict[str, object]]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    summary_matches = list(
        re.finditer(r"SUMMARY OF RESULTS for partitions:\s*(\d+)", text)
    )
    if not summary_matches:
        raise ValueError(f"{path}: missing final SUMMARY OF RESULTS table")
    summary_match = summary_matches[-1]
    partition_number = int(summary_match.group(1))
    invocation_start = text.rfind("Running Distributed DCOPF", 0, summary_match.start())
    if invocation_start < 0:
        raise ValueError(f"{path}: missing Running Distributed DCOPF header")
    invocation = text[invocation_start:]
    pre_summary = text[invocation_start : summary_match.start()]
    summary = text[summary_match.start() :]

    case_file = _match_required(
        r"^\s*case file\s*=\s*(.+?)\s*$", invocation, "case file", path
    )
    case = Path(case_file).stem
    header_partition = int(
        _match_required(
            r"^\s*num\. Partitions\s*=\s*(\d+)\s*$",
            invocation,
            "partition count",
            path,
        )
    )
    if header_partition != partition_number:
        raise ValueError(
            f"{path}: header partition {header_partition} disagrees with summary {partition_number}"
        )
    solver = _match_required(
        r"^\s*admmSolver\s*=\s*(\S+)\s*$", invocation, "ADMM solver", path
    )
    rho = float(
        _match_required(
            r"^\s*initialRho\s*=\s*([-+0-9.eE]+)\s*$",
            invocation,
            "initial rho",
            path,
        )
    )
    spec = _classify_spec(case, partition_number, solver, rho)

    config: dict[str, object] = {
        "figure": spec.figure,
        "case": case,
        "partition_number": partition_number,
        "case_file": case_file,
        "admm_solver": solver,
        "initial_rho": rho,
        "tolerance": float(
            _match_required(
                r"^\s*tol\s*=\s*([-+0-9.eE]+)\s*$", invocation, "tolerance", path
            )
        ),
        "max_iterations": int(
            _match_required(
                r"^\s*maxIter\s*=\s*(\d+)\s*$", invocation, "maximum iterations", path
            )
        ),
        "time_limit_seconds": float(
            _match_required(
                r"^\s*timeLimit\s*=\s*([-+0-9.eE]+)\s*$",
                invocation,
                "time limit",
                path,
            )
        ),
        "log_interval": int(
            _match_required(
                r"^\s*logInterval\s*=\s*(\d+)\s*$", invocation, "log interval", path
            )
        ),
        "r_value": float(
            _match_required(
                r"^\s*r_value\s*=\s*([-+0-9.eE]+)\s*$", invocation, "r_value", path
            )
        ),
        "seed": int(
            _match_required(r"^\s*seed\s*=\s*(\d+)\s*$", invocation, "seed", path)
        ),
        "threads": int(
            _match_required(
                r"Run Bipartite ADMM with threads\s*=\s*(\d+)",
                invocation,
                "Julia thread count",
                path,
            )
        ),
        "true_dc_objective": float(
            _match_required(
                r"True DC objective:\s*([-+0-9.eE]+)",
                invocation,
                "centralized DC objective",
                path,
            )
        ),
        "log_path": str(path.resolve()),
    }

    details = _detailed_results(pre_summary)
    detail_by_method = {
        method: details[index] if index < len(details) else {}
        for index, method in enumerate(METHODS)
    }
    summary_pattern = re.compile(
        r"^\s*(BFS|MILP|GNN)\s*\|\s*([-+0-9.eE]+)\s*\|\s*(\d+)\s*\|"
        r"\s*([-+0-9.eE]+)\s*\|\s*([-+0-9.eE]+)\s*\|",
        flags=re.MULTILINE,
    )
    summary_rows: dict[str, tuple[float, int, float, float]] = {}
    for match in summary_pattern.finditer(summary):
        summary_rows[match.group(1)] = (
            float(match.group(2)),
            int(match.group(3)),
            float(match.group(4)),
            float(match.group(5)),
        )
    missing_methods = [method for method in METHODS if method not in summary_rows]
    if missing_methods:
        raise ValueError(f"{path}: final summary is missing methods {missing_methods}")

    rows: list[dict[str, object]] = []
    for method in METHODS:
        partition_time, iterations, admm_time, admm_objective = summary_rows[method]
        detail = detail_by_method[method]
        detail_iterations = detail.get("iterations")
        if detail_iterations not in (None, iterations):
            raise ValueError(
                f"{path}: {method} detailed iterations {detail_iterations} "
                f"disagree with summary {iterations}"
            )
        row = dict(config)
        row.update(
            {
                "method": method,
                "partition_time_seconds": partition_time,
                "admm_time_seconds": admm_time,
                "total_time_seconds": partition_time + admm_time,
                "iterations": iterations,
                "admm_objective": admm_objective,
                "termination_status": detail.get("status", ""),
                "primal_residual_l2": detail.get("pres_l2", ""),
                "primal_residual_linf": detail.get("pres_linf", ""),
                "dual_residual_l2": detail.get("dres_l2", ""),
                "dual_residual_linf": detail.get("dres_linf", ""),
                "true_objective_difference": detail.get("true_obj_diff", ""),
            }
        )
        rows.append(row)
    return spec, rows


def _parse_logs(paths: Iterable[Path]) -> tuple[list[ExperimentSpec], list[dict[str, object]]]:
    specs: list[ExperimentSpec] = []
    rows: list[dict[str, object]] = []
    errors: list[str] = []
    for path in paths:
        try:
            spec, parsed = _parse_log(path)
        except (OSError, ValueError) as error:
            errors.append(str(error))
            continue
        specs.append(spec)
        rows.extend(parsed)
    if errors:
        formatted = "\n".join(f"  - {error}" for error in errors)
        raise SystemExit(f"Failed to parse Section 3.3 logs:\n{formatted}")
    if not rows:
        raise SystemExit("No complete Section 3.3 DC-OPF logs were found")
    return specs, rows


def _close(left: float, right: float) -> bool:
    return math.isclose(left, right, rel_tol=1.0e-10, abs_tol=1.0e-12)


def _validate_rows(
    rows: Sequence[Mapping[str, object]],
    expected_specs: Sequence[ExperimentSpec],
    *,
    require_archived_statuses: bool,
    check_objectives: bool,
) -> dict[str, object]:
    expected_jobs = {spec.key for spec in expected_specs}
    grouped: dict[tuple[int, str, int], list[Mapping[str, object]]] = defaultdict(list)
    for row in rows:
        key = (int(row["figure"]), str(row["case"]), int(row["partition_number"]))
        grouped[key].append(row)
    actual_jobs = set(grouped)
    errors: list[str] = []
    if actual_jobs != expected_jobs:
        missing = sorted(expected_jobs - actual_jobs)
        extra = sorted(actual_jobs - expected_jobs)
        errors.append(f"Unexpected Section 3.3 job grid; missing={missing}, extra={extra}")

    for spec in expected_specs:
        job_rows = grouped.get(spec.key)
        if job_rows is None:
            continue
        method_counts = Counter(str(row["method"]) for row in job_rows)
        if method_counts != Counter(METHODS):
            errors.append(f"{spec.key}: method rows are {dict(method_counts)}")
            continue
        for row in job_rows:
            method = str(row["method"])
            checks = (
                (str(row["admm_solver"]) == spec.solver, "solver"),
                (_close(float(row["initial_rho"]), spec.rho), "rho"),
                (_close(float(row["tolerance"]), TOLERANCE), "tolerance"),
                (int(row["max_iterations"]) == MAX_ITERATIONS, "max iterations"),
                (_close(float(row["time_limit_seconds"]), TIME_LIMIT_SECONDS), "time limit"),
                (int(row["log_interval"]) == LOG_INTERVAL, "log interval"),
                (_close(float(row["r_value"]), R_VALUE), "r_value"),
                (int(row["seed"]) == SEED, "seed"),
                (float(row["partition_time_seconds"]) >= 0.0, "partition time"),
                (float(row["admm_time_seconds"]) >= 0.0, "ADMM time"),
                (int(row["iterations"]) > 0, "iterations"),
            )
            for passed, label in checks:
                if not passed:
                    errors.append(f"{spec.key}/{method}: invalid {label}: {row.get(label, '')}")

            status = str(row["termination_status"])
            if status not in {
                "ADMM_TERMINATION_OPTIMAL",
                "ADMM_TERMINATION_TIME_LIMIT",
            }:
                errors.append(f"{spec.key}/{method}: unexpected status {status}")

            if check_objectives:
                expected_objective = OBJECTIVE_FINGERPRINTS[spec.case]
                observed_objective = float(row["true_dc_objective"])
                if not math.isclose(
                    observed_objective, expected_objective, rel_tol=1.0e-8, abs_tol=1.0e-4
                ):
                    errors.append(
                        f"{spec.key}/{method}: centralized objective {observed_objective:.12g} "
                        f"does not match MATPOWER fingerprint {expected_objective:.12g}"
                    )

            if require_archived_statuses:
                expected_status = (
                    "ADMM_TERMINATION_TIME_LIMIT"
                    if spec.figure == 13
                    and spec.case == "case1888rte"
                    and spec.partition_number == 10
                    else "ADMM_TERMINATION_OPTIMAL"
                )
                if status != expected_status:
                    errors.append(
                        f"{spec.key}/{method}: archived status {status!r}, expected {expected_status}"
                    )

    status_counts = Counter(
        str(row["termination_status"]) or "UNKNOWN" for row in rows
    )
    return {
        "status": "passed" if not errors else "failed",
        "expected_job_count": len(expected_jobs),
        "actual_job_count": len(actual_jobs),
        "row_count": len(rows),
        "expected_method_count_per_job": len(METHODS),
        "expected_methods": list(METHODS),
        "require_archived_statuses": require_archived_statuses,
        "check_objective_fingerprints": check_objectives,
        "experiment_profile": _experiment_profile(expected_specs),
        "termination_status_counts": dict(sorted(status_counts.items())),
        "missing_jobs": [list(key) for key in sorted(expected_jobs - actual_jobs)],
        "unexpected_jobs": [list(key) for key in sorted(actual_jobs - expected_jobs)],
        "errors": errors,
        "warnings": [],
    }


def _aggregate(rows: Sequence[Mapping[str, object]]) -> list[dict[str, object]]:
    by_case_method: dict[tuple[str, str], list[Mapping[str, object]]] = defaultdict(list)
    by_partition_method: dict[tuple[int, str], list[Mapping[str, object]]] = defaultdict(list)
    for row in rows:
        if int(row["figure"]) == 13:
            by_case_method[(str(row["case"]), str(row["method"]))].append(row)
        else:
            by_partition_method[(int(row["partition_number"]), str(row["method"]))].append(row)

    aggregates: list[dict[str, object]] = []
    for case in FIGURE_13_CASES:
        if not any(key[0] == case for key in by_case_method):
            continue
        for method in METHODS:
            selected = by_case_method[(case, method)]
            aggregates.append(
                {
                    "figure": 13,
                    "case": case,
                    "partition_number": "",
                    "aggregation": "arithmetic_mean_over_partitions",
                    "method": method,
                    "sample_count": len(selected),
                    "partition_time_seconds": arithmetic_mean(
                        float(row["partition_time_seconds"]) for row in selected
                    ),
                    "admm_time_seconds": arithmetic_mean(
                        float(row["admm_time_seconds"]) for row in selected
                    ),
                    "iterations": arithmetic_mean(float(row["iterations"]) for row in selected),
                }
            )
    for partition_number in FIGURE_14_PARTITIONS:
        if not any(key[0] == partition_number for key in by_partition_method):
            continue
        for method in METHODS:
            selected = by_partition_method[(partition_number, method)]
            aggregates.append(
                {
                    "figure": 14,
                    "case": "case57",
                    "partition_number": partition_number,
                    "aggregation": "per_partition",
                    "method": method,
                    "sample_count": len(selected),
                    "partition_time_seconds": arithmetic_mean(
                        float(row["partition_time_seconds"]) for row in selected
                    ),
                    "admm_time_seconds": arithmetic_mean(
                        float(row["admm_time_seconds"]) for row in selected
                    ),
                    "iterations": arithmetic_mean(float(row["iterations"]) for row in selected),
                }
            )

    normalization_groups: dict[tuple[int, str, object], list[dict[str, object]]] = defaultdict(list)
    for aggregate in aggregates:
        partition_key: object = (
            aggregate["partition_number"] if int(aggregate["figure"]) == 14 else "mean"
        )
        normalization_groups[
            (int(aggregate["figure"]), str(aggregate["case"]), partition_key)
        ].append(aggregate)
    for selected in normalization_groups.values():
        for aggregate in selected:
            aggregate["total_time_seconds"] = float(aggregate["partition_time_seconds"]) + float(
                aggregate["admm_time_seconds"]
            )
        max_time = max(float(aggregate["total_time_seconds"]) for aggregate in selected)
        max_iterations = max(float(aggregate["iterations"]) for aggregate in selected)
        for aggregate in selected:
            aggregate["normalized_partition_time"] = (
                float(aggregate["partition_time_seconds"]) / max_time if max_time > 0 else 0.0
            )
            aggregate["normalized_admm_time"] = (
                float(aggregate["admm_time_seconds"]) / max_time if max_time > 0 else 0.0
            )
            aggregate["normalized_total_time"] = (
                float(aggregate["total_time_seconds"]) / max_time if max_time > 0 else 0.0
            )
            aggregate["normalized_iterations"] = (
                float(aggregate["iterations"]) / max_iterations if max_iterations > 0 else 0.0
            )
    return aggregates


def _aggregate_index(
    rows: Sequence[Mapping[str, object]],
) -> dict[tuple[int, str, int | None, str], Mapping[str, object]]:
    result = {}
    for row in rows:
        partition = int(row["partition_number"]) if row["partition_number"] != "" else None
        result[(int(row["figure"]), str(row["case"]), partition, str(row["method"]))] = row
    return result


def _draw_iterations(axis, groups: Sequence[object], labels: Sequence[str], values) -> None:
    width = 0.25
    x_positions = list(range(len(groups)))
    offsets = {"BFS": -width, "MILP": 0.0, "GNN": width}
    for method in METHODS:
        axis.bar(
            [position + offsets[method] for position in x_positions],
            [values(group, method) for group in groups],
            width=width,
            color=METHOD_COLORS[method],
            label=method,
        )
    axis.set_xticks(x_positions)
    axis.set_xticklabels(labels)
    axis.set_ylabel("Normalized iterations", fontsize=13)
    axis.set_ylim(0.0, 1.08)
    axis.grid(axis="y", alpha=0.22)
    axis.legend(ncol=3, fontsize=11)


def _draw_time(axis, groups: Sequence[object], labels: Sequence[str], values) -> None:
    width = 0.25
    x_positions = list(range(len(groups)))
    offsets = {"BFS": -width, "MILP": 0.0, "GNN": width}
    for method in METHODS:
        positions = [position + offsets[method] for position in x_positions]
        partition_values = [values(group, method, "normalized_partition_time") for group in groups]
        admm_values = [values(group, method, "normalized_admm_time") for group in groups]
        axis.bar(
            positions,
            partition_values,
            width=width,
            color=METHOD_LIGHT_COLORS[method],
        )
        axis.bar(
            positions,
            admm_values,
            width=width,
            bottom=partition_values,
            color=METHOD_COLORS[method],
            label=method,
        )
    axis.set_xticks(x_positions)
    axis.set_xticklabels(labels)
    axis.set_ylabel("Normalized time", fontsize=13)
    axis.set_ylim(0.0, 1.08)
    axis.grid(axis="y", alpha=0.22)
    axis.legend(ncol=3, fontsize=11)


def _save_figure(figure, base_path: Path) -> None:
    figure.tight_layout()
    figure.savefig(base_path.with_suffix(".png"), dpi=200)
    figure.savefig(base_path.with_suffix(".pdf"))


def _plot_figure_13(aggregates: Sequence[Mapping[str, object]], output: Path) -> None:
    pyplot = get_pyplot()
    index = _aggregate_index(aggregates)
    groups = [case for case in FIGURE_13_CASES if (13, case, None, "BFS") in index]
    if not groups:
        return

    def iterations(case, method):
        return float(index[(13, case, None, method)]["normalized_iterations"])

    def times(case, method, field):
        return float(index[(13, case, None, method)][field])

    labels = groups
    figure, axis = pyplot.subplots(figsize=(10, 5))
    _draw_iterations(axis, groups, labels, iterations)
    axis.set_xlabel("MATPOWER case", fontsize=13)
    _save_figure(figure, output / "figures" / "figure_13_iterations")
    pyplot.close(figure)

    figure, axis = pyplot.subplots(figsize=(10, 5))
    _draw_time(axis, groups, labels, times)
    axis.set_xlabel("MATPOWER case", fontsize=13)
    _save_figure(figure, output / "figures" / "figure_13_time")
    pyplot.close(figure)

    figure, axes = pyplot.subplots(1, 2, figsize=(14, 4.8))
    _draw_iterations(axes[0], groups, labels, iterations)
    _draw_time(axes[1], groups, labels, times)
    axes[0].set_title("(a) Iterations")
    axes[1].set_title("(b) Total time")
    for axis in axes:
        axis.set_xlabel("MATPOWER case")
    _save_figure(figure, output / "figures" / "figure_13")
    pyplot.close(figure)


def _plot_figure_14(aggregates: Sequence[Mapping[str, object]], output: Path) -> None:
    pyplot = get_pyplot()
    index = _aggregate_index(aggregates)
    groups = [
        partition
        for partition in FIGURE_14_PARTITIONS
        if (14, "case57", partition, "BFS") in index
    ]
    if not groups:
        return

    def iterations(partition, method):
        return float(index[(14, "case57", partition, method)]["normalized_iterations"])

    def times(partition, method, field):
        return float(index[(14, "case57", partition, method)][field])

    labels = [str(partition) for partition in groups]
    figure, axis = pyplot.subplots(figsize=(10, 5))
    _draw_iterations(axis, groups, labels, iterations)
    axis.set_xlabel("Partition number", fontsize=13)
    _save_figure(figure, output / "figures" / "figure_14_iterations")
    pyplot.close(figure)

    figure, axis = pyplot.subplots(figsize=(10, 5))
    _draw_time(axis, groups, labels, times)
    axis.set_xlabel("Partition number", fontsize=13)
    _save_figure(figure, output / "figures" / "figure_14_time")
    pyplot.close(figure)

    figure, axes = pyplot.subplots(1, 2, figsize=(14, 4.8))
    _draw_iterations(axes[0], groups, labels, iterations)
    _draw_time(axes[1], groups, labels, times)
    axes[0].set_title("(a) Iterations")
    axes[1].set_title("(b) Total time")
    for axis in axes:
        axis.set_xlabel("Partition number")
    _save_figure(figure, output / "figures" / "figure_14")
    pyplot.close(figure)


def _smoke_reference_comparison(
    rows: Sequence[Mapping[str, object]],
) -> dict[str, object]:
    selected = {
        str(row["method"]): row
        for row in rows
        if int(row["figure"]) == 13
        and str(row["case"]) == "case30"
        and int(row["partition_number"]) == 3
    }
    reference_max_iterations = max(
        float(value["iterations"]) for value in REFERENCE_SMOKE_CASE30_P3.values()
    )
    reference_max_time = max(
        float(value["partition_time_seconds"]) + float(value["admm_time_seconds"])
        for value in REFERENCE_SMOKE_CASE30_P3.values()
    )
    observed_max_iterations = max(
        (float(row["iterations"]) for row in selected.values()),
        default=1.0,
    )
    observed_max_time = max(
        (float(row["total_time_seconds"]) for row in selected.values()),
        default=1.0,
    )

    entries: list[dict[str, object]] = []
    for method in METHODS:
        observed = selected.get(method)
        if observed is None:
            continue
        reference = REFERENCE_SMOKE_CASE30_P3[method]
        reference_iterations = float(reference["iterations"])
        reference_partition = float(reference["partition_time_seconds"])
        reference_admm = float(reference["admm_time_seconds"])
        reference_total = reference_partition + reference_admm
        observed_iterations = float(observed["iterations"])
        observed_partition = float(observed["partition_time_seconds"])
        observed_admm = float(observed["admm_time_seconds"])
        observed_total = float(observed["total_time_seconds"])
        entries.append(
            {
                "figure": 13,
                "case": "case30",
                "partition_number": 3,
                "method": method,
                "observed_iterations": observed_iterations,
                "reference_iterations": reference_iterations,
                "iterations_difference": observed_iterations - reference_iterations,
                "observed_partition_time_seconds": observed_partition,
                "reference_partition_time_seconds": reference_partition,
                "observed_admm_time_seconds": observed_admm,
                "reference_admm_time_seconds": reference_admm,
                "observed_total_time_seconds": observed_total,
                "reference_total_time_seconds": reference_total,
                "total_time_difference_seconds": observed_total - reference_total,
                "observed_normalized_iterations": observed_iterations
                / observed_max_iterations,
                "reference_normalized_iterations": reference_iterations
                / reference_max_iterations,
                "observed_normalized_total_time": observed_total / observed_max_time,
                "reference_normalized_total_time": reference_total / reference_max_time,
            }
        )

    status_counts = Counter(str(row["termination_status"]) or "UNKNOWN" for row in rows)
    max_iteration_difference = max(
        (abs(float(entry["iterations_difference"])) for entry in entries),
        default=0.0,
    )
    max_normalized_iteration_difference = max(
        (
            abs(
                float(entry["observed_normalized_iterations"])
                - float(entry["reference_normalized_iterations"])
            )
            for entry in entries
        ),
        default=0.0,
    )
    return {
        "reference": (
            "experiments_logs.zip Section 3.3 case30/P=3 raw result "
            "(case30/51455118)"
        ),
        "notes": [
            "This is the exact archived point selected by --mode smoke, not the Figure 13 mean over P=3,...,10.",
            "Iteration counts are the primary deterministic comparison.",
            "Runtime is hardware- and environment-dependent and is reported without pass/fail gating.",
        ],
        "summary": {
            "compared_entries": len(entries),
            "all_iteration_values_match": max_iteration_difference <= 1.0e-9,
            "maximum_absolute_iteration_difference": max_iteration_difference,
            "maximum_absolute_normalized_iteration_difference": max_normalized_iteration_difference,
            "termination_status_counts": dict(sorted(status_counts.items())),
        },
        "entries": entries,
    }


def _reference_comparison(
    aggregates: Sequence[Mapping[str, object]],
    rows: Sequence[Mapping[str, object]],
    *,
    smoke_profile: bool = False,
) -> dict[str, object]:
    if smoke_profile:
        return _smoke_reference_comparison(rows)

    index = _aggregate_index(aggregates)
    entries: list[dict[str, object]] = []

    for case, method_values in REFERENCE_FIGURE_13.items():
        reference_max_iterations = max(value[0] for value in method_values.values())
        reference_max_time = max(value[1] for value in method_values.values())
        for method in METHODS:
            key = (13, case, None, method)
            if key not in index:
                continue
            observed = index[key]
            reference_iterations, reference_time = method_values[method]
            entry = {
                "figure": 13,
                "case": case,
                "partition_number": None,
                "method": method,
                "observed_iterations": float(observed["iterations"]),
                "reference_iterations": reference_iterations,
                "iterations_difference": float(observed["iterations"]) - reference_iterations,
                "observed_total_time_seconds": float(observed["total_time_seconds"]),
                "reference_total_time_seconds": reference_time,
                "total_time_difference_seconds": float(observed["total_time_seconds"])
                - reference_time,
                "observed_normalized_iterations": float(observed["normalized_iterations"]),
                "reference_normalized_iterations": reference_iterations
                / reference_max_iterations,
                "observed_normalized_total_time": float(observed["normalized_total_time"]),
                "reference_normalized_total_time": reference_time / reference_max_time,
            }
            entries.append(entry)

    for partition_number, method_values in REFERENCE_FIGURE_14.items():
        reference_max_iterations = max(value[0] for value in method_values.values())
        reference_max_time = max(value[1] + value[2] for value in method_values.values())
        for method in METHODS:
            key = (14, "case57", partition_number, method)
            if key not in index:
                continue
            observed = index[key]
            reference_iterations, reference_partition, reference_admm = method_values[method]
            reference_time = reference_partition + reference_admm
            entries.append(
                {
                    "figure": 14,
                    "case": "case57",
                    "partition_number": partition_number,
                    "method": method,
                    "reference_initial_rho": 2000.0,
                    "observed_iterations": float(observed["iterations"]),
                    "reference_iterations": reference_iterations,
                    "iterations_difference": float(observed["iterations"])
                    - reference_iterations,
                    "observed_partition_time_seconds": float(observed["partition_time_seconds"]),
                    "reference_partition_time_seconds": reference_partition,
                    "observed_admm_time_seconds": float(observed["admm_time_seconds"]),
                    "reference_admm_time_seconds": reference_admm,
                    "observed_total_time_seconds": float(observed["total_time_seconds"]),
                    "reference_total_time_seconds": reference_time,
                    "total_time_difference_seconds": float(observed["total_time_seconds"])
                    - reference_time,
                    "observed_normalized_iterations": float(observed["normalized_iterations"]),
                    "reference_normalized_iterations": reference_iterations
                    / reference_max_iterations,
                    "observed_normalized_total_time": float(observed["normalized_total_time"]),
                    "reference_normalized_total_time": reference_time / reference_max_time,
                }
            )

    status_counts = Counter(str(row["termination_status"]) or "UNKNOWN" for row in rows)
    max_iteration_difference = max(
        (abs(float(entry["iterations_difference"])) for entry in entries), default=0.0
    )
    max_normalized_iteration_difference = max(
        (
            abs(
                float(entry["observed_normalized_iterations"])
                - float(entry["reference_normalized_iterations"])
            )
            for entry in entries
        ),
        default=0.0,
    )
    figure_14_entries = [entry for entry in entries if int(entry["figure"]) == 14]
    observed_figure_14_rhos = sorted(
        {
            float(row["initial_rho"])
            for row in rows
            if int(row["figure"]) == 14
        }
    )
    figure_14_reference_applicable = observed_figure_14_rhos == [2000.0]
    max_figure_14_iteration_difference = max(
        (abs(float(entry["iterations_difference"])) for entry in figure_14_entries),
        default=0.0,
    )
    max_figure_14_partition_time_difference = max(
        (
            abs(
                float(entry["observed_partition_time_seconds"])
                - float(entry["reference_partition_time_seconds"])
            )
            for entry in figure_14_entries
        ),
        default=0.0,
    )
    max_figure_14_admm_time_difference = max(
        (
            abs(
                float(entry["observed_admm_time_seconds"])
                - float(entry["reference_admm_time_seconds"])
            )
            for entry in figure_14_entries
        ),
        default=0.0,
    )
    all_figure_14_reference_values_match = (
        figure_14_reference_applicable
        and len(figure_14_entries) == len(FIGURE_14_PARTITIONS) * len(METHODS)
        and max_figure_14_iteration_difference <= 1.0e-9
        and max_figure_14_partition_time_difference <= 1.0e-9
        and max_figure_14_admm_time_difference <= 1.0e-9
    )
    return {
        "reference": "experiments_logs.zip final Section 3.3 folders used for paper Figures 13-14",
        "figure_14_reference_profile": REPORTED_FIGURE_14_PROFILE,
        "observed_figure_14_rhos": observed_figure_14_rhos,
        "figure_14_reference_applicable": figure_14_reference_applicable,
        "notes": [
            "Iteration counts are the primary deterministic comparison.",
            "Runtime is hardware- and environment-dependent and is reported without pass/fail gating.",
            "The archived case1888rte/P=10 runs hit the 7200-second limit for all methods.",
            "Figure 14 references are the exact retained rho=2000 values behind the published arXiv panels.",
            "They are explicitly not applicable to a fresh manuscript-literal rho=1000 Figure 14 run.",
        ],
        "summary": {
            "compared_entries": len(entries),
            "all_iteration_values_match": max_iteration_difference <= 1.0e-9,
            "maximum_absolute_iteration_difference": max_iteration_difference,
            "maximum_absolute_normalized_iteration_difference": max_normalized_iteration_difference,
            "figure_14_reference_applicable": figure_14_reference_applicable,
            "all_figure_14_reference_values_match": all_figure_14_reference_values_match,
            "maximum_absolute_figure_14_iteration_difference": max_figure_14_iteration_difference,
            "maximum_absolute_figure_14_partition_time_difference_seconds": max_figure_14_partition_time_difference,
            "maximum_absolute_figure_14_admm_time_difference_seconds": max_figure_14_admm_time_difference,
            "termination_status_counts": dict(sorted(status_counts.items())),
        },
        "entries": entries,
    }


def _reference_validation_errors(
    comparison: Mapping[str, object],
    *,
    mode: str,
    smoke_profile: bool,
) -> list[str]:
    summary = comparison.get("summary")
    if not isinstance(summary, Mapping):
        return ["Section 3.3 reference comparison has no valid summary"]
    errors: list[str] = []
    if (mode == "archived" or smoke_profile) and not bool(
        summary.get("all_iteration_values_match")
    ):
        profile = "archived grid" if mode == "archived" else "case30/P=3 smoke point"
        errors.append(
            f"Section 3.3 {profile} iteration values do not match embedded references"
        )
    if mode == "archived" and summary.get("figure_14_reference_applicable") is False:
        errors.append(
            "Archived Figure 14 data do not use the required historical rho=2000 profile"
        )
    if mode == "archived" and summary.get("all_figure_14_reference_values_match") is False:
        errors.append(
            "Archived Figure 14 iterations or component times do not match published references"
        )
    return errors


def _merge_reference_validation(
    validation: Mapping[str, object],
    comparison: Mapping[str, object],
    *,
    mode: str,
    smoke_profile: bool,
) -> dict[str, object]:
    """Return the final report after deterministic reference validation."""

    merged = dict(validation)
    errors = list(validation.get("errors", ()))
    errors.extend(
        _reference_validation_errors(
            comparison,
            mode=mode,
            smoke_profile=smoke_profile,
        )
    )
    merged["errors"] = errors
    merged["status"] = "passed" if not errors else "failed"
    merged["reference_summary"] = comparison.get("summary")
    return merged


def _enforce_iteration_reference(
    comparison: Mapping[str, object],
    *,
    mode: str,
    smoke_profile: bool,
) -> None:
    """Compatibility wrapper used by callers that want an immediate failure."""

    errors = _reference_validation_errors(
        comparison,
        mode=mode,
        smoke_profile=smoke_profile,
    )
    if errors:
        raise SystemExit(errors[0])


def _runtime_summary(rows: Sequence[Mapping[str, object]]) -> dict[str, object]:
    by_figure: dict[int, float] = defaultdict(float)
    by_case: dict[str, float] = defaultdict(float)
    for row in rows:
        total = float(row["total_time_seconds"])
        by_figure[int(row["figure"])] += total
        by_case[str(row["case"])] += total
    total = sum(by_figure.values())
    return {
        "measured_partition_plus_admm_seconds": total,
        "measured_partition_plus_admm_hours": total / 3600.0,
        "by_figure_seconds": {str(key): value for key, value in sorted(by_figure.items())},
        "by_case_seconds": dict(sorted(by_case.items())),
        "reported_rho2000_archive_full_sweep_seconds": 118954.649,
        "reported_rho2000_archive_full_sweep_hours": 118954.649 / 3600.0,
        "rho1000_retained_comparison_sweep_seconds": 122889.742,
        "rho1000_retained_comparison_sweep_hours": 122889.742 / 3600.0,
        "scope_note": (
            "Times sum only bipartization and ADMM times reported by the driver; dependency "
            "installation, compilation, centralized Ipopt solve, and process startup are excluded."
        ),
    }


def _spec_signature(spec: ExperimentSpec) -> tuple[int, str, int, str, float]:
    return (*spec.key, spec.solver, spec.rho)


def _parse_mode_expected_specs(
    specs: Sequence[ExperimentSpec],
) -> tuple[ExperimentSpec, ...]:
    actual = {_spec_signature(spec) for spec in specs}
    profiles = (SMOKE_SPECS, FRESH_FULL_SPECS, ARCHIVED_SPECS)
    for expected in profiles:
        expected_signatures = {_spec_signature(spec) for spec in expected}
        if len(specs) == len(expected) and actual == expected_signatures:
            return expected

    fresh = {_spec_signature(spec) for spec in FRESH_FULL_SPECS}
    missing = sorted(fresh - actual)
    extra = sorted(actual - fresh)
    raise SystemExit(
        "--mode parse expects the documented smoke grid, the fresh manuscript-literal "
        "rho=1000 full grid, or the reported archived rho=2000 full grid; "
        f"missing_from_fresh_full={missing}, extra_or_profile_mismatch={extra}"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    add_common_arguments(
        parser, default_output=REPRODUCTION_ROOT / "output" / "section_3_3"
    )
    parser.add_argument(
        "--matpower-dir",
        type=Path,
        default=DEFAULT_MATPOWER_DIR,
        help=(
            "Directory containing case30.m, case57.m, case89pegase.m, case118.m, "
            "case300.m, and case1888rte.m. Fresh runs default to the bundled "
            f"directory {DEFAULT_MATPOWER_DIR}; use this option to override it."
        ),
    )
    parser.add_argument(
        "--python",
        type=Path,
        dest="pdmo_python",
        help="Python executable with numpy, torch, and torch_geometric (sets PDMO_PYTHON).",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    validate_common_arguments(args)
    output = prepare_mode_output(args.output, args.mode)

    fresh = args.mode in ("smoke", "full")
    if args.mode == "smoke":
        expected_specs = SMOKE_SPECS
    elif args.mode == "archived":
        expected_specs = ARCHIVED_SPECS
    else:
        expected_specs = FRESH_FULL_SPECS
    jobs: list[Job] = []
    job_results = []
    provenance_inputs: list[Path] = []
    fresh_log_paths: list[Path] = []
    reported_panel_validation: dict[str, object] | None = None

    if fresh:
        case_files = _matpower_inputs(args.matpower_dir, expected_specs)
        python_executable = _resolve_python(args.pdmo_python)
        _check_python_dependencies(python_executable)
        _check_pycall_dependencies(args.julia, python_executable)
        model_weights = REPO_ROOT / "advanced" / "src" / "gnn" / "GNN" / "model_weights_10.pth"
        if not model_weights.is_file():
            raise SystemExit(f"Bundled GNN weights not found: {model_weights}")
        jobs = _jobs_for_specs(args, expected_specs, case_files)
        if args.mode == "full":
            print(
                "Full Section 3.3 sweep: archived partition+ADMM time is about 34.1 hours "
                "with one worker; setup and compilation are additional.",
                flush=True,
            )
        job_results = run_jobs(
            jobs,
            log_root=output / "raw",
            cwd=legacy_workdir(),
            workers=args.jobs,
            resume=not args.no_resume,
            environment={"PDMO_PYTHON": python_executable},
        )
        write_json(output / "job_results.json", job_results_as_dicts(job_results))
        failures = failed_jobs(job_results)
        if failures:
            write_provenance(
                output,
                section="Section 3.3 / DC-OPF Figures 13-14",
                args=args,
                jobs=jobs,
                inputs=tuple(case_files.values()) + (model_weights,),
                notes=("One or more fresh Julia subprocesses failed; inspect job_results.json.",),
            )
            names = ", ".join(result.name for result in failures)
            raise SystemExit(f"Section 3.3 Julia jobs failed: {names}")
        fresh_log_paths = [Path(result.log_path) for result in job_results]
        provenance_inputs.extend(case_files.values())
        provenance_inputs.append(model_weights)
    elif args.mode == "archived":
        provenance_inputs.append(args.archive)

    if fresh:
        parsed_specs, rows = _parse_logs(fresh_log_paths)
    else:
        with source_logs(args, ARCHIVE_SECTION, output / "raw") as source:
            if args.mode == "archived":
                paths = _archived_final_logs(source)
                reported_panel_validation = _preserve_reported_figure_14_panels(
                    source, output
                )
                write_json(output / "reported_source_panels.json", reported_panel_validation)
            else:
                # If parse points at an extracted copy of the original archive,
                # use the same explicit final selection.  Otherwise parse the
                # caller's complete/smoke raw-log directory.
                try:
                    paths = _archived_final_logs(source)
                except SystemExit:
                    paths = collect_logs(source)
            parsed_specs, rows = _parse_logs(paths)
        if args.mode == "parse":
            expected_specs = _parse_mode_expected_specs(parsed_specs)

    experiment_profile = _experiment_profile(expected_specs)
    write_json(
        output / "experiment_profile.json",
        {"mode": args.mode, **experiment_profile},
    )
    artifact_scope = {
        "archived": "archived_reconstruction",
        "parse": "caller_supplied_parse_input",
        "smoke": "validation_only_subset",
        "full": "fresh_paper_grid",
    }[args.mode]
    if experiment_profile["classification"] == "historical_reported_archive":
        publication_warning = (
            "This reconstructs the published Figure 14 rho=2000 source profile; "
            "the manuscript caption instead states rho=1000."
        )
    elif args.mode == "smoke":
        publication_warning = (
            "Smoke artifacts validate one documented subset and are not complete paper figures."
        )
    else:
        publication_warning = (
            "This follows the manuscript-literal Figure 14 rho=1000 profile and is not "
            "the historical rho=2000 profile that generated the published panels."
        )
    write_json(
        output / "artifact_profile.json",
        {
            "mode": args.mode,
            "artifact_scope": artifact_scope,
            "publication_warning": publication_warning,
            "section_experiment_profile": experiment_profile,
        },
    )
    validation = _validate_rows(
        rows,
        expected_specs,
        require_archived_statuses=args.mode == "archived",
        check_objectives=fresh or args.mode == "archived",
    )
    if reported_panel_validation is not None:
        validation["reported_source_panel_validation"] = reported_panel_validation
        if reported_panel_validation["status"] != "passed":
            validation["errors"].extend(reported_panel_validation["errors"])
            validation["status"] = "failed"
    if validation["status"] != "passed":
        write_json(output / "validation.json", validation)
        formatted = "\n".join(f"  - {error}" for error in validation["errors"])
        raise SystemExit(f"Section 3.3 validation failed:\n{formatted}")
    if args.mode == "archived":
        for row in rows:
            row["log_path"] = _archive_log_identifier(args.archive, row)
    rows = sorted(
        rows,
        key=lambda row: (
            int(row["figure"]),
            FIGURE_13_CASES.index(str(row["case"]))
            if str(row["case"]) in FIGURE_13_CASES
            else 999,
            int(row["partition_number"]),
            METHODS.index(str(row["method"])),
        ),
    )
    aggregates = _aggregate(rows)
    write_csv(output / "runs.csv", RUN_FIELDS, rows)
    write_csv(output / "aggregates.csv", AGGREGATE_FIELDS, aggregates)

    smoke_keys = {spec.key for spec in SMOKE_SPECS}
    expected_keys = {spec.key for spec in expected_specs}
    smoke_profile = (
        len(expected_specs) == len(SMOKE_SPECS) and expected_keys == smoke_keys
    )
    comparison = _reference_comparison(
        aggregates,
        rows,
        smoke_profile=smoke_profile,
    )
    write_json(output / "reference_comparison.json", comparison)
    write_json(output / "runtime_summary.json", _runtime_summary(rows))
    validation = _merge_reference_validation(
        validation,
        comparison,
        mode=args.mode,
        smoke_profile=smoke_profile,
    )
    write_json(output / "validation.json", validation)
    if validation["status"] != "passed":
        formatted = "\n".join(f"  - {error}" for error in validation["errors"])
        raise SystemExit(f"Section 3.3 validation failed:\n{formatted}")

    if not args.no_plots:
        _plot_figure_13(aggregates, output)
        _plot_figure_14(aggregates, output)

    write_provenance(
        output,
        section="Section 3.3 / distributed DC-OPF Figures 13-14",
        args=args,
        jobs=jobs,
        inputs=provenance_inputs,
        notes=(
            "Figure 13: six MATPOWER cases, P=3:10, original ADMM, rho=100.",
            f"Experiment profile: {experiment_profile['classification']}.",
            (
                "Reported Figure 14: case57, P=13:18, doubly linearized ADMM, rho=2000, retained folder case57_flip_2000, jobs 51523865-51523870."
                if experiment_profile["classification"] == "historical_reported_archive"
                else "Fresh manuscript-literal Figure 14: case57, P=13:18, doubly linearized ADMM, rho=1000."
            ),
            "The manuscript caption says rho=1000; the exact retained source panels and their data use rho=2000.",
            (
                "Archived mode byte-preserves and SHA256-verifies both retained published Figure 14 source PNGs."
                if args.mode == "archived"
                else "Fresh/parse outputs remain separate from retained published source PNGs."
            ),
            "Fresh jobs use one Julia process per (case,P); BFS, MILP, and GNN share one METIS partition.",
            "Archived reported rho=2000 and fresh manuscript-literal rho=1000 profiles are never merged.",
            "The archived full sweep contains three valid time-limited method results at case1888rte/P=10.",
            "Reported archived partition+ADMM time is approximately 33.0 hours sequentially, excluding setup.",
        ),
    )
    print(f"Wrote Section 3.3 artifacts to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
